# Generated by Django 6.0 on 2026-06-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('extra_phone', models.CharField(blank=True, default='', max_length=20)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=200)),
                ('payment_method', models.CharField(choices=[('naqt', 'Naqt'), ('karta', 'Karta')], default='naqt', max_length=10)),
                ('delivery_method', models.CharField(choices=[('yetkazish', 'Yetkazib berish'), ('olib_ketish', 'Kelib olib ketish')], default='yetkazish', max_length=20)),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='books.order')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
